#!/usr/bin/env tsx
/**
 * Weekly Alpha Report generator.
 *
 * Deliverable B — sprints/alpha-validation-readiness.md:
 * "Mỗi tuần generate (script hoặc manual từ dashboard JSON)"
 *
 * Reads data/telemetry/events.jsonl, aggregates the last 7 days using the
 * same logic as the Operations Dashboard, and writes a dated report under
 * reports/. Does NOT touch reports/weekly-alpha.md — that file stays the
 * blank template; "Product Notes" (quotes, surprises, churn) still require
 * a human to fill in after talking to the recruiter.
 *
 * Usage: pnpm run report:weekly [--days=7] [--out=reports/weekly-alpha-YYYY-MM-DD.md]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildOperationsDashboard } from "../src/modules/operations/operations-dashboard-aggregator.js";
import type { TelemetryEvent } from "../src/shared/telemetry/types.js";

function parseArg(name: string, fallback: string): string {
  const prefix = `--${name}=`;
  const found = process.argv.find((a) => a.startsWith(prefix));
  return found ? found.slice(prefix.length) : fallback;
}

const days = Number(parseArg("days", "7"));
const eventsPath = resolve("data/telemetry/events.jsonl");

function readEvents(): TelemetryEvent[] {
  if (!existsSync(eventsPath)) return [];
  return readFileSync(eventsPath, "utf-8")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => JSON.parse(line) as TelemetryEvent);
}

function mdTable(headers: string[], rows: string[][]): string {
  if (rows.length === 0) {
    return `| ${headers.join(" | ")} |\n| ${headers.map(() => "---").join(" | ")} |\n| ${headers.map(() => "—").join(" | ")} |`;
  }
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${r.join(" | ")} |`),
  ].join("\n");
}

function pct(v: number): string {
  return `${(v * 100).toFixed(1)}%`;
}

const now = new Date();
const windowStart = new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
const weekStartLabel = windowStart.toISOString().slice(0, 10);

const allEvents = readEvents();
const weekEvents = allEvents.filter((e) => new Date(e.timestamp) >= windowStart);

if (allEvents.length === 0) {
  console.warn(
    `report:weekly — data/telemetry/events.jsonl is empty. Writing an all-zero report ` +
      `(expected before real Alpha CVs are processed).`,
  );
}

const dashboard = buildOperationsDashboard(weekEvents, now);

const qualified = weekEvents.filter((e) => e.event_type === "candidate_qualified");
const successes = weekEvents.filter((e) => e.event_type === "resume_import_completed");
const activeDays = new Set(successes.map((e) => new Date(e.timestamp).toISOString().slice(0, 10)))
  .size;

const reasons = dashboard.ai.why_people_override_ai;
const missing = dashboard.ai.top_missing_fields;
const fieldStats = dashboard.ai.field_review_stats;
const fieldDuration = dashboard.ai.field_edit_duration;
const byPriority = dashboard.ai.review_by_priority;

const overrideTable = mdTable(
  ["Field", "Override %"],
  [...fieldStats]
    .sort((a, b) => b.override_rate - a.override_rate)
    .slice(0, 10)
    .map((f) => [f.field, pct(f.override_rate)]),
);

const acceptedTable = mdTable(
  ["Field", "Acceptance %"],
  [...fieldStats]
    .sort((a, b) => b.acceptance_rate - a.acceptance_rate)
    .slice(0, 10)
    .map((f) => [f.field, pct(f.acceptance_rate)]),
);

const missingTable = mdTable(
  ["Field", "Count"],
  missing.map((f) => [f.field, String(f.count)]),
);

const reasonsTable = mdTable(
  ["Reason", "Count"],
  reasons.map((r) => [r.reason, String(r.count)]),
);

const queueTable = mdTable(
  ["Priority", "Reviewed %", "Override %"],
  byPriority.map((p) => [p.priority, pct(p.percent_of_reviews), pct(p.override_rate)]),
);

const durationTable = mdTable(
  ["Field", "Avg time"],
  [...fieldDuration]
    .sort((a, b) => b.avg_duration_ms - a.avg_duration_ms)
    .map((f) => [f.field, f.avg_duration_formatted]),
);

const report = `# Weekly Alpha Report — Week of ${weekStartLabel}

> Auto-generated by \`pnpm run report:weekly\` from \`data/telemetry/events.jsonl\`.
> No AI. No database. Product Notes below still need a human.

## Summary

- CVs processed this week: ${successes.length}
- Qualified candidates: ${qualified.length}
- Active recruiter days: ${activeDays}

## Top Override Fields

${overrideTable}

## Top Accepted Fields

${acceptedTable}

## Average TTQC

| Metric | Value |
| --- | --- |
| Mean | ${dashboard.business.average_ttqc.today_formatted} |
| Median | ${dashboard.business.median_ttqc.today_formatted} |

## Top Missing Fields

${missingTable}

## Top Review Reasons

${reasonsTable}

## Review Queue Effectiveness

${queueTable}

## TTQC Breakdown by Field

${durationTable}

## Product Notes

### Recruiter quotes (nguyên văn)

> _(điền sau phỏng vấn — xem docs/recruiter-interview-guide.md)_

### Quote ↔ Telemetry đối chiếu

| Quote | Metric | Có bằng chứng? |
| --- | --- | --- |
| | | |

### Surprises

-

### Churn risks observed

See \`docs/what-would-make-recruiter-stop.md\`

---

## What did we learn this week?

> *(Không phải "What will we build?")*

-

---

## Vấn đề theo dõi (0–2)

| Vấn đề | Bằng chứng tuần này | Tích lũy (rule of 10) |
| --- | --- | --- |
| | | |

---

*Weekly Product Review ritual: \`docs/weekly-product-review.md\`*
*Generated: ${now.toISOString()} · Window: last ${days} days · Events in window: ${weekEvents.length} / ${allEvents.length} total*
`;

const outPath = resolve(parseArg("out", `reports/weekly-alpha-${weekStartLabel}.md`));
mkdirSync(resolve("reports"), { recursive: true });
writeFileSync(outPath, report, "utf-8");
console.log(`report:weekly — wrote ${outPath} (${weekEvents.length} events in window)`);
